### ISSUE TITLE
Search Indexer 

### ISSUE THREAD

**Issue by mbs5mz** [omattei/CavTutor#48]
Should there be multiple search indexers, one for each tutor, tutee, course, and institution? I noticed the indexer for tutor was completed already, even though that was my responsibility.

**Comment by omattei** [comment]
I don't think it's worth making separate searches for the other stuff. If you can help me fix some of the stuff Leandra suggested in the "ISA CS 4501: Project 4 Grade Team 16" email that would be awesome, though. Gonna submit what we've got in about 1hr.
---
Copy and pasted from email since UVA email servers are always delayed.
